server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://8.136.199.219:3306/db_credit?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '!qwe&123'

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

knife4j:
  enable: true
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent:
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
